services:
#  bot:
#    build: .
#    env_file:
#      - .env
#    depends_on:
#      - db
#      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datemate
    ports:
      - "5432:5432"
#  redis:
#    image: redis:7
#    ports:
#      - "6379:6379"